"""empty message

Revision ID: 2f548c70f6dc
Revises: 05909376a113
Create Date: 2024-09-21 14:12:46.135021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f548c70f6dc'
down_revision = '05909376a113'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('header', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('subject', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('body', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('link', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('closure', sa.String(length=120), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=80),
               nullable=False)

    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.drop_column('closure')
        batch_op.drop_column('link')
        batch_op.drop_column('body')
        batch_op.drop_column('subject')
        batch_op.drop_column('header')

    # ### end Alembic commands ###
