"""empty message

Revision ID: 3c9be4fc5ded
Revises: 78e6ef331c47
Create Date: 2024-09-21 18:34:37.221963

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c9be4fc5ded'
down_revision = '78e6ef331c47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exam_session')
    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.alter_column('content',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=1200),
               existing_nullable=False)
        batch_op.drop_constraint('email_template_content_key', type_='unique')
        batch_op.drop_column('body')
        batch_op.drop_column('header')
        batch_op.drop_column('closure')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('email_template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('closure', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('header', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('body', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
        batch_op.create_unique_constraint('email_template_content_key', ['content'])
        batch_op.alter_column('content',
               existing_type=sa.String(length=1200),
               type_=sa.VARCHAR(length=120),
               existing_nullable=False)

    op.create_table('exam_session',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('date', sa.VARCHAR(length=120), autoincrement=False, nullable=False),
    sa.Column('employee_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['user.id'], name='exam_session_employee_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='exam_session_pkey'),
    sa.UniqueConstraint('score', name='exam_session_score_key')
    )
    # ### end Alembic commands ###
