"""empty message

Revision ID: 8cf34b98c3f6
Revises: f70ac1b7a561
Create Date: 2024-09-21 11:40:48.831605

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cf34b98c3f6'
down_revision = 'f70ac1b7a561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('its_active', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('its_active')

    # ### end Alembic commands ###
